server:
  port: 8080
spring:
  ai:
    deepseek:
      api-key: sk-d5561d9c6c5545199629c3f41d7f6728 # 填写 DeepSeek Api Key, 改成你自己的
      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
      chat:
        options:
          model: deepseek-chat # 使用哪个模型
          temperature: 0.8 # 温度值

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

